// FloodShield email alert endpoint for Vercel using Resend.
// Required environment variables: RESEND_API_KEY, ALERT_EMAIL
// Optional: FROM_EMAIL, ALLOWED_ORIGIN

let lastSentAt = 0;
const COOLDOWN_MS = 60_000;

function cleanText(value, max = 80) {
  return String(value ?? '').replace(/[\r\n<>]/g, ' ').trim().slice(0, max);
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export default async function handler(req, res) {
  res.setHeader('Cache-Control', 'no-store');

  const allowedOrigin = process.env.ALLOWED_ORIGIN;
  const origin = req.headers.origin || '';
  if (allowedOrigin && origin !== allowedOrigin) {
    return res.status(403).json({ ok: false, error: 'Origin not allowed.' });
  }

  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ ok: false, error: 'POST only.' });
  }

  const now = Date.now();
  if (now - lastSentAt < COOLDOWN_MS) {
    const wait = Math.ceil((COOLDOWN_MS - (now - lastSentAt)) / 1000);
    return res.status(429).json({ ok: false, error: `Please wait ${wait}s before sending another demo alert.` });
  }

  const apiKey = process.env.RESEND_API_KEY;
  const to = process.env.ALERT_EMAIL;
  const from = process.env.FROM_EMAIL || 'FloodShield <onboarding@resend.dev>';
  if (!apiKey || !to) {
    return res.status(503).json({ ok: false, error: 'Email backend is not configured yet.' });
  }

  const risk = Math.max(0, Math.min(100, Number(req.body?.risk) || 0));
  const level = cleanText(req.body?.level || (risk >= 75 ? 'CRITICAL' : risk >= 55 ? 'HIGH RISK' : 'WATCH'), 20);
  const location = cleanText(req.body?.location || 'Delhi', 60);
  const rain6 = Math.max(0, Number(req.body?.rain6) || 0).toFixed(1);
  const sentAt = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const safeLevel = escapeHtml(level);
  const safeLocation = escapeHtml(location);
  const subject = `🚨 FloodShield ${level} Alert — ${location}`;
  const html = `
    <div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;background:#081522;color:#eef6fb;border-radius:16px;overflow:hidden;border:1px solid #22384d">
      <div style="background:#b91c1c;padding:20px 24px">
        <div style="font-size:13px;letter-spacing:1px">FLOODSHIELD EARLY WARNING</div>
        <h1 style="margin:6px 0 0;font-size:27px">🚨 ${safeLevel} FLOOD ALERT</h1>
      </div>
      <div style="padding:24px">
        <p style="margin-top:0;color:#b9cbd8">FloodShield has detected an elevated modeled flood-risk condition.</p>
        <table style="width:100%;border-collapse:collapse;color:#eef6fb">
          <tr><td style="padding:10px;border-bottom:1px solid #26394a">Location</td><td style="padding:10px;border-bottom:1px solid #26394a;text-align:right"><b>${safeLocation}</b></td></tr>
          <tr><td style="padding:10px;border-bottom:1px solid #26394a">Risk score</td><td style="padding:10px;border-bottom:1px solid #26394a;text-align:right"><b>${Math.round(risk)}/100</b></td></tr>
          <tr><td style="padding:10px;border-bottom:1px solid #26394a">Next 6h rainfall</td><td style="padding:10px;border-bottom:1px solid #26394a;text-align:right"><b>${rain6} mm</b></td></tr>
          <tr><td style="padding:10px">Generated</td><td style="padding:10px;text-align:right"><b>${escapeHtml(sentAt)} IST</b></td></tr>
        </table>
        <div style="margin-top:20px;padding:14px;background:#3a1717;border:1px solid #7f1d1d;border-radius:10px;line-height:1.5">
          Avoid waterlogged or low-lying roads and underpasses. Follow official DDMA/IMD advisories for emergency decisions.
        </div>
        <p style="font-size:12px;color:#8298aa;margin-bottom:0;margin-top:22px">Prototype alert generated by FloodShield. This is not an official government warning.</p>
      </div>
    </div>`;

  try {
    const providerResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ from, to: [to], subject, html })
    });

    const data = await providerResponse.json().catch(() => ({}));
    if (!providerResponse.ok) {
      console.error('Resend error', data);
      return res.status(502).json({ ok: false, error: data?.message || 'Email provider rejected the message.' });
    }

    lastSentAt = now;
    return res.status(200).json({ ok: true, id: data.id || null, status: 'sent' });
  } catch (error) {
    console.error(error);
    return res.status(500).json({ ok: false, error: 'Could not contact email provider.' });
  }
}
